### ISSUE TITLE
Rewrite in Go

### ISSUE THREAD

**Issue by dgryski** [dgryski/tinygo-test-corpus#6]
This started out as a bash for loop, which then became a bash script, and then finally a python script.  Move this fully to Go.  While we're at it, move the repo config out of the main binary.

**Comment by soypat** [comment]
I can maybe take a look at this over the weekend

**Comment by soypat** [comment]
Ok so I got this so far for rewriting the `repos` structure for all ye whippersnappers out there
```go
type T struct {
	Repo    string
	Tags    string
	Subdirs []string
}
```

And can be generated via 

```python

print("var repos = []T{\n")
for repo in repos:
    print(f'{{\n\tRepo:"{repo["repo"]}",')
    if 'tags' in repo:
        print(f'\tTags:"{repo["tags"]}",')
    if 'subdirs' in repo:
        print('\tSubdirs: []string{')
        for subdir in repo['subdirs']:
            print(f'\t\t"{subdir}",')
        print("},")
    print("},")
print("}")
```
